### ISSUE TITLE
Add default "None" option to 2nd-tier dropdowns

### ISSUE THREAD

**Issue by engelen** [engelen/bulk-actions#4]
For fields with a second dropdown, there should be an additional option with an indication that an option has to be selected (e.g. "Select Post Visibility"). Otherwise, the user might accidentally update to a non-desired value. Suggestion props @markhowellsmead.

**Comment by markhowellsmead** [comment]
Suggest that a validator checks to see whether the selected post status is "None", and if so, then the action is blocked.

**Comment by engelen** [comment]
You mean client-side (as well as server-side, obviously), right?

**Comment by markhowellsmead** [comment]
Yes, to avoid an unnecessary round-trip. (As the backend is pretty slow, any opportunity to prevent an unnecessary page refresh is recommended.)

**Comment by engelen** [comment]
Fully agree, good point.

**Comment by engelen** [comment]
Progress in https://github.com/engelen/bulk-actions/tree/%234-default-none-option-secondary-dropdowns.

**Comment by engelen** [comment]
Done https://github.com/engelen/bulk-actions/commit/daadf6e7dfe3206d40a40751f525f1c94144faa7.
