### ISSUE TITLE
Plugin file naming

### ISSUE THREAD

**Issue by markhowellsmead** [engelen/bulk-actions#9]
The file name "bulk-actions.php" and possibly the plugin name “Advanced Bulk Actions” are insufficiently unique. If there is another plugin in the WordPress Plugin Repository with the same name or file name – even if the plugin folder name is unique – then you might encounter issues. 

(When a newer version of the plugin becomes available, the WordPress backend will indicate that there's an update for your plugin, and overwrite it with the other one.)

I'd recommend re-naming the plugin and using “engelen” as a prefix.

**Comment by engelen** [comment]
Is there a WordPress core Trac issue detailing this behaviour? I recall there being one, but I can't find it. Renaming the plugin in the repository is impossible; the only possibility would be to rename the file (and I'm not even sure that won't break anything).

**Comment by markhowellsmead** [comment]
Puuh, now you're asking. I ran into this issue when I called my plugin “Test Plugin” during development and it wanted to update to a completely different one!

If you rename the file and/or folder, it will deactivate it when anyone updates to the newer version. Are you a member of https://wpch.slack.com? If so, then ask there; there's bound to be someone who knows immediately where definitive information is.

**Comment by engelen** [comment]
I know, but better to do it now than to wait until the plugin is bigger; if any other plugin having a file named `bulk-actions.php` in the plugin folder could cause harm, this should be fixed sooner rather than later. I'll run an experiment or two and ask in the Slack channel.

**Comment by engelen** [comment]
Marking as wontfix because the plugin name can't be changed in the WP.org repository and because only the folder name needs to be unique (not the file name inside the folder), which makes it a lot less of a problem.
